name: Node.js CI

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: short_sha
        name: Get short SHA
        run: echo "sha7=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build:rollup --entryFileNames 'kirara-${{ steps.short_sha.outputs.sha7 }}.mjs'
      - uses: actions/upload-artifact@v4
        with:
          name: kirara-${{ steps.short_sha.outputs.sha7 }}
          path: dist
          compression-level: 9
