name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build:rollup --entryFileNames 'kirara-${{ github.event.release.tag_name }}.mjs'
      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: dist
      - run: echo * | xargs -n 1 zstd --rm -19
        working-directory: dist
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*
